### GET ALL USERS
GET http://localhost:3333/users HTTP/1.1

### GET ONE USERS
GET http://localhost:3333/users/673319106a2e6950351e8c3f HTTP/1.1
Content-Type: application/json

### GET ONE USERS
GET http://localhost:3333/users/1 HTTP/1.1
Content-Type: application/json


### ADD USER
POST http://localhost:3333/users HTTP/1.1
Content-Type: application/json

{
   "name": "Gustavo",
   "email": "gstv@planner.com",
   "url": "https://cdn.esahubble.org/archives/images/screen/jwst_in_space-cc.jpg"
}

### Delete user by id
DELETE http://localhost:3333/users/6733209971ffbdd3d1ac5969 HTTP/1.1
Content-Type: application/json


### Create trip
POST http://localhost:3333/trips HTTP/1.1
Content-Type: application/json

{
    "destination": "Japan",
    "starts_at": "2024-11-20T05:00:00.000Z",
    "ends_at": "2024-11-25T05:00:00.000Z",
    "is_confirmed": false,
     "created_by": "Gustavo",
}

mongodb+srv://gstvcalca:HImcT4qW9ElORn2L@cluster0.piknxu4.mongodb.net/
