### GET ALL USERS
GET http://localhost:3333/users HTTP/1.1

### GET ONE USERS
GET http://localhost:3333/users/673319106a2e6950351e8c3f HTTP/1.1
Content-Type: application/json

### GET ONE USERS
GET http://localhost:3333/users/1 HTTP/1.1
Content-Type: application/json


### ADD USER
POST http://localhost:3333/users HTTP/1.1
Content-Type: application/json

{
   "name": "Gustavo",
   "email": "gstv@planner.com",
   "url": "https://cdn.esahubble.org/archives/images/screen/jwst_in_space-cc.jpg"
}

### Delete user by id
DELETE http://localhost:3333/users/6733209971ffbdd3d1ac5969 HTTP/1.1
Content-Type: application/json

### Get trips
GET http://localhost:3333/trips HTTP/1.1


### Create trip
POST http://localhost:3333/trips HTTP/1.1
Content-Type: application/json

{
  "destination": "Paris",
  "starts_at": "2024-12-01T09:00:00Z",
  "ends_at": "2024-12-10T18:00:00Z",
  "is_confirmed": true,
  "created_by": "user@example.com",
  "img_url": "https://example.com/paris.jpg",
  "description": "A delightful trip to Paris during the holiday season.",
  "guests": [
    {
      "name": "John Doe",
      "email": "john.doe@example.com",
      "url": "https://example.com/john"
    },
    {
      "name": "Jane Smith",
      "email": "jane.smith@example.com",
      "url": "https://example.com/jane"
    }
  ],
  "infos": [
    {
      "title": "Hotel Info",
      "description": "We will stay at the Ritz Paris."
    },
    {
      "title": "Flight Info",
      "description": "Flight AC123 on December 1st at 9:00 AM."
    }
  ],
  "links": [
    {
      "title": "Hotel Website",
      "url": "https://ritzparis.com"
    },
    {
      "title": "Flight Details",
      "url": "https://airline.com/booking"
    }
  ],
  "activities": [
    {
      "title": "City Tour",
      "occurs_at": "2024-12-02T10:00:00Z"
    },
    {
      "title": "Eiffel Tower Visit",
      "occurs_at": "2024-12-03T14:00:00Z"
    }
  ]
}

### Get trip detail
GET http://localhost:3333/trips/67390e527c820dcc50229ebf HTTP/1.1

### Get all trips
GET http://localhost:3333/trips HTTP/1.1